import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { gql, GraphQLClient } from 'graphql-request'
import Section from '@/components/Section'
import Navbar from '@/components/Navbar'

export const getStaticProps = async () => {
  const url = process.env.ENDPOINT
  const graphQLClient = new GraphQLClient(url, {
    headers: {
      "Authorization" : process.env.GRAPH_CMS_TOKEN
    }
  })

  const query = gql`
  query {
    videos{
      createdAt,
      id,
      title,
      description,
      seen,
      slug,
      tags,
      thimbnail{
        url
      }
    }
  }
  `
  const data = await graphQLClient.request(query)
const videos = data.videos
  return {
    props : {
      videos,
    }
  }
}


const inter = Inter({ subsets: ['latin'] })

export default function Home({videos}) {



  const randomVideo = ( videos ) => {
    return videos[Math.floor(Math.random() * videos.length)]
  }

// function who filter the videos by genre
const filterVideos = (videos, genre) => {
  return videos.filter((video) => video.tags.includes(genre))
}

const unSeenVideos = (videos) => {
  return videos.filter(video => video.seen == false || video.seen == null)
}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Navbar />
       <div className='app'>
        <div className='main-video'>
          <img src={randomVideo(videos).thimbnail.url} alt={randomVideo(videos).title}/>
        </div> 
        <div className='video-feed'>
          <Section genre={'Recommended for you'} videos={unSeenVideos(videos)}/>
          <Section genre={'Clown'} videos={filterVideos(videos, 'Clown')}/>
          <Section genre={'Monsters'} videos={filterVideos(videos, 'Monsters')}/>
          <Section genre={'Classic'} videos={filterVideos(videos, 'Classic')}/>
          <Section genre={'Possession'} videos={filterVideos(videos, 'Possession')}/>
          <Section genre={'Serial Killers'} videos={filterVideos(videos, 'Serial Killers')}/>

       </div>
       </div>
      </main>
    </>
  )
}
