import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { gql, GraphQLClient } from 'graphql-request'
import Section from '@/components/Section'

export const getStaticProps = async () => {
  const url = process.env.ENDPOINT
  const graphQLClient = new GraphQLClient(url, {
    headers: {
      "Authorization" : process.env.GRAPH_CMS_TOKEN
    }
  })

  const query = gql`
  query {
    videos{
      createdAt,
      id,
      title,
      description,
      seen,
      slug,
      tags,
      thimbnail{
        url
      }
    }
  }
  `
  const data = await graphQLClient.request(query)
const videos = data.videos
  return {
    props : {
      videos,
    }
  }
}


const inter = Inter({ subsets: ['latin'] })

export default function Home({videos}) {
console.log(videos.length)


  const randomVideo = ( videos ) => {
    return videos[Math.floor(Math.random() * videos.length)]
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <div className='app'>
        <div className='main-video'>
          <img src={randomVideo(videos).thimbnail.url} alt={randomVideo(videos).title}/>
        </div> 
       </div>
       <div className='video-feed'>
          <Section genre={'Vampires'}/>
          <Section genre={'Monsters'}/>
          <Section genre={'Zombies'}/>
          <Section genre={'Possession'}/>
          <Section genre={'Serial Killers'}/>

       </div>
      </main>
    </>
  )
}
